env:
  browser: true
  commonjs: true
  es2021: true
  jest/globals: true
extends:
  - eslint:recommended
  - prettier
overrides: []
globals:
  browser: true
  __dirname: true
  # Common
  loadAwsProfiles: true
  saveAwsProfile: true
  saveAwsProfiles: true
parserOptions:
  ecmaVersion: latest
rules: {}
plugins:
  - jest
